### ISSUE TITLE
Project License

### ISSUE THREAD

**Issue by Joschuka** [onepiecefreak3/etc1tool#1]
Hello,
I've been working during the last months on a Noesis plugin to view game assets used in Koei Tecmo games : 
https://forum.xentax.com/viewtopic.php?f=16&t=21666
https://github.com/Joschuka/Project-G1M

I've recently been asked to add support for Hyrule Warriors Legends (3DS) and discovered that the g1t texture files used in that game use some ETC1 compression that your tool is able to deal with. 
Could you please give me permission to use your code in my Noesis plugin ? If so I'll credit you in both the my xentax thread and the code files.

**Comment by onepiecefreak3** [comment]
This tool is pretty old, and I rellay just referenced rg_etc1 for what it's worth. So I'd say, since I never put a license on it, this code may be as free as rg_etc1 itself.
rg_etc1 was originally created and licensed by Rich Geldreich, with the following license agreement:

// Copyright (c) 2012 Rich Geldreich
//
// This software is provided 'as-is', without any express or implied
// warranty.  In no event will the authors be held liable for any damages
// arising from the use of this software.
//
// Permission is granted to anyone to use this software for any purpose,
// including commercial applications, and to alter it and redistribute it
// freely, subject to the following restrictions:
//
// 1. The origin of this software must not be misrepresented; you must not
// claim that you wrote the original software. If you use this software
// in a product, an acknowledgment in the product documentation would be
// appreciated but is not required.
//
// 2. Altered source versions must be plainly marked as such, and must not be
// misrepresented as being the original software.
//
// 3. This notice may not be removed or altered from any source distribution.
//
//------------------------------------------------------------------------------

Follow it, and this repo may be handled the same.
